##
## EPITECH PROJECT, 2018
## zappy_ai
## File description:
## Makefile for the project zappy_ai
##

NAME	=	zappy_ai

all:	$(NAME)

$(NAME):
		@echo zappy_ai

clean:
		@echo zappy_ai clean

fclean:	clean
		@echo zappy_ai fclean

re:		fclean all